### ISSUE TITLE
Error with Solaris 11

### ISSUE THREAD

**Issue by chiiiisay** [sschwartzman/newrelic-unix-plugin#11]
Hi,

 I installed the plugin on a Solaris 11 server and I get this error. Please help me.

12:04[root@wpslab2:/opt/IBM/Recursos/Plugin_NewRelic/newrelic_unix_plugin/logs]# tail -3000f newrelic_unix_plugin.err
The java class could not be loaded. java.lang.UnsupportedClassVersionError: (com/chocolatefactory/newrelic/plugins/unix/Main) bad major version at offset=6

**Comment by sschwartzman** [comment]
I think it's auto-detecting an old version of Java on your server. You may need to manually set which Java on your server to use, by uncommenting and setting the PLUGIN_JAVA variable at the top of the script.

To test that, I've updated pluginctl.sh to output Java version info to the .err file. Can you download the new version (link below), run "./pluginctl.sh start" at command line and send me what it returns to the screen and to the logs?

Updated pluginctl.sh: https://raw.githubusercontent.com/sschwartzman/newrelic-unix-plugin/master/pluginctl.sh

Thanks,
Seth
