### ISSUE TITLE
Missing path on  pluginctl.sh

### ISSUE THREAD

**Issue by Pitsyjulio** [sschwartzman/newrelic-unix-plugin#14]
Hello.

just to let you know that in the file pluginctl.sh, in line 53  "/jar" it is not included, we added manualy, and it worked ok.

we recommend update the plug in. 

thanks.

**Comment by marcostijerina** [comment]
Hello,
Just adding some more specific information regarding the missing "/jar".  

$ tail -n1 logs/newrelic_unix_plugin.err  
**Error: Could not find or load main class com.chocolatefactory.newrelic.plugins.unix.Main**

Running:
- OS X El Capitan Version 10.11.4
- Unix Agent version: 3.4.1

The solution was a slight modification of the  path in line 54 of the pluginctl.sh:
$ vim +54 pluginctl.sh

Changed the following:
**Before**
PLUGIN_JAVA_OPTS="-Xms16m -Xmx128m -cp $PLUGIN_PATH/bin/newrelic_unix_plugin.jar:$PLUGIN_PATH/lib/metrics_publish-2.0.1.jar:$PLUGIN_PATH/lib/json-simple-1.1.1.jar"

**After**
PLUGIN_JAVA_OPTS="-Xms16m -Xmx128m -cp $PLUGIN_PATH/bin**/jar**/newrelic_unix_plugin.jar:$PLUGIN_PATH/lib/metrics_publish-2.0.1.jar:$PLUGIN_PATH/lib/json-simple-1.1.1.jar"

**Below is the directory structure of the extracted .zip file:** 
./newrelic-unix-plugin-master/.settings
**./newrelic-unix-plugin-master/bin/jar**
./newrelic-unix-plugin-master/bin
./newrelic-unix-plugin-master/config/logs
./newrelic-unix-plugin-master/config
./newrelic-unix-plugin-master/dist
./newrelic-unix-plugin-master/lib
./newrelic-unix-plugin-master/logs
./newrelic-unix-plugin-master/src/com/chocolatefactory/newrelic/plugins/unix
./newrelic-unix-plugin-master/src/com/chocolatefactory/newrelic/plugins/utils
./newrelic-unix-plugin-master/src/com/chocolatefactory/newrelic/plugins
./newrelic-unix-plugin-master/src/com/chocolatefactory/newrelic
./newrelic-unix-plugin-master/src/com/chocolatefactory
./newrelic-unix-plugin-master/src/com
./newrelic-unix-plugin-master/src
./newrelic-unix-plugin-master

Thanks

**Comment by sschwartzman** [comment]
Thanks for pointing that out - there was an issue in the build process that made the JAR appear under JAR. Fixed now. Thanks!

**Comment by sschwartzman** [comment]
Actually, I figured out what's going on - you were downloading the zip of the whole Repo, not the distribution file of the plugin itself. You can download that here: https://github.com/sschwartzman/newrelic-unix-plugin/blob/master/dist/newrelic_unix_plugin.tar.gz?raw=true
