### ISSUE TITLE
Memory stats not being published

### ISSUE THREAD

**Issue by cvervais** [sschwartzman/newrelic-unix-plugin#15]
After upgrading the RAM in my system, the Unix Plugin is no longer publishing memory usage up to New Relic. I'm not seeing any errors logged or any other trouble and all other metrics are looking normal. 

OS X 10.11.3

iMac-3:logs cvervais$ tail -100 newrelic_unix_plugin.err 
Plugin location: /Users/cvervais/newrelic_unix_plugin
Java location: /usr/bin/java
Java version: java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
iMac-3:logs cvervais$ tail -100 newrelic_unix_plugin.log
[2016-02-29 10:36:00,895] INFO  com.chocolatefactory.newrelic.plugins.unix.UnixAgentFactory - Unix Agent version: 3.4.1
iMac-3:logs cvervais$ uname -a
Darwin iMac-3.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

**Comment by sschwartzman** [comment]
Can you run the plugin in debug mode to see what's going on? To do so, set debug to true in plugin.json, and set log_level to "debug" in newrelic.json, start the plugin and wait a couple minutes, then attach the files here.

**Comment by sschwartzman** [comment]
Any luck with this? Going through old issues and this one is still open. I can close if you no longer see the issue or haven't the time to try the debug steps. Let me know.

**Comment by sschwartzman** [comment]
I fixed this and verified it on my Mac so, I'm going to go ahead and close it. Please re-open if you try the latest plugin out and it still doesn't work for you. Thanks!
