### ISSUE TITLE
Technical Question: Port

### ISSUE THREAD

**Issue by CarlosAlvarezG** [sschwartzman/newrelic-unix-plugin#18]
Hello Team

I wanted to know if we could setup SSL port instead of 80, as we don't want to open this port in our production environment. The following setup works well in QA:
"proxy_host": "xxx.xxx.com", 
"proxy_port": "80" 

Regards.
Carlos.

**Comment by sschwartzman** [comment]
You should be able to use any port for proxy, including https proxies.
