### ISSUE TITLE
Unable to start this plugin

### ISSUE THREAD

**Issue by DavidGarciaCat** [sschwartzman/newrelic-unix-plugin#21]
Hello there,

I am trying to use this plugin, setting up my mac, and I am getting this error:

```
Plugin location: /Users/<username>/.newrelic-unix-plugin
Java location: /usr/bin/java
Java version: java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
Error: Could not find or load main class com.chocolatefactory.newrelic.plugins.unix.Main
```

Any idea? I have cloned this repository, by the way.

Thanks,

**Comment by Bobspadger** [comment]
I had a similar issue with cloning the repo.

Downloading the tar.gz file from the frontpage  / readme worked.

**Comment by DavidGarciaCat** [comment]
@Bobspadger Thanks for the tip - downloading the tar.gz file the service is running. Thanks!
