### ISSUE TITLE
Poll Cycle

### ISSUE THREAD

**Issue by JorgeAlaniz** [sschwartzman/newrelic-unix-plugin#22]
Hi
We are having issues with this plugin, Seems that the poll cycle of the plugin is breaking the 10 minutes rules from new relic and sometimes it appears in gray and then it goes back to green and keeps that iterating behavior (summary metrics get cleared everytime). Is there anyway to troubleshoot the poll cycle of the plugin?

When starting the plugin we have the next msg: 
hadmin@alpogsdzone002:/u01/newrelic/newrelic_unix_plugin$ ./pluginctl.sh status 
Plugin location: /u01/newrelic/newrelic_unix_plugin 
Java location: /u01/Oracle/Middleware/jdk160_35/bin/java 
awk: syntax error near line 1 
awk: illegal statement near line 1 
Java version: 
Checking New Relic Unix Plugin 
New Relic Unix Plugin is running with PID 48717

There is no errors in the log, I've the plugin in Debug mode. Btw this is a Solaris box

**Comment by JorgeAlaniz** [comment]
Can you please let us know what the current poll cycle for the plugin is? (60, 600? Seconds) and do you know how much time in average it takes to collect and send data to NR?
Thanks!

**Comment by sschwartzman** [comment]
The poll cycle is regulated by the Plugin SDK, which sends the data every 60 seconds. I'm not sure I can do anything about the gaps but if it's just one or some of the graphs, it may be a specific command that's taking too long.

Is it all graphs for the plugin instance that have a gap, or just certain ones?

**Comment by sschwartzman** [comment]
@JorgeAlaniz I've updated the Solaris portion of the plugin to not have long-running commands (like vmstat with a long delay), so it should be reporting every interval now and you shouldn't see drop-outs. Can you try downloading the latest version, running with it and seeing if that resolves your issues?

**Comment by JorgeAlaniz** [comment]
Thanks for the inputs, will check with user and let you know the results :+1:
