### ISSUE TITLE
No data in unix plugin in New Relic

### ISSUE THREAD

**Issue by srivathsansr** [sschwartzman/newrelic-unix-plugin#24]
Hi team,

We are not able to view any data in the plugin section of New relic analytic tool for the past couple of days. We tried to contact New relic support but we were asked to contact you people since you are the provider.
This is the link to that plugin.
[https://rpm.newrelic.com/accounts/1075023/plugins/18134](url)
user name: dipens
id: dipens@petco.com

Please help us out with this issue. Let me know if you need more clarification.
You can reach me through my mail, **_"srivas@petco.com"_**

Thanks in advance.
![aem issue](https://cloud.githubusercontent.com/assets/20198111/16439044/a16cd1a0-3d69-11e6-95be-fbaff4be2dcc.JPG)

**Comment by sschwartzman** [comment]
Please upgrade to the latest version, as per the documentation: https://github.com/sschwartzman/newrelic-unix-plugin#note-if-all-of-your-summary-metrics-disappeared-like-this-below-upgrade-to-the-latest-version
