### ISSUE TITLE
%Memory Utilization appears to be incorrectly overstated on AIX.

### ISSUE THREAD

**Issue by dmacisso** [sschwartzman/newrelic-unix-plugin#25]
%Memory Utilization appears to be incorrectly overstated on AIX.
According to my calculations memory utilization on my AIX server is 28% see calculations below
 # mymem
Total Memory =  60.0 G
Used Memory =   16.9 G
Free Memory =   43.1 G
Used Percent =  28.00 %

# cat /usr/local/bin/mymem
#!/usr/bin/ksh
totmem=$(svmon -O unit=auto |grep memory | awk '{ print $2 }'| sed 's/G//g')
usedmem=$(svmon -O unit=auto |grep "in use" | awk '{ print $3 }'| sed 's/G//g')
# start bc with a two-way pipe
bc|&
# print -p writes to the pipe
print -p scale=2
print -p $totmem - $usedmem
# read -p reads from the pipe
read -p freemem
print -p $usedmem/$totmem*100
read -p pctmem
echo "Total Memory =\t$totmem G"
echo "Used Memory =\t$usedmem G"
echo "Free Memory =\t$freemem G"
echo "Used Percent =\t$pctmem %"

However the plugin reports 96.3% usage

Permalink
https://rpm.newrelic.com/accounts/1231377/plugins/20410

**Comment by sschwartzman** [comment]
I have a fix in for this - it turned out to be pretty simple. I was running "svmon -G" instead of just "svmon", so I was reporting on the global host memory, not that of the LPAR you're in. [Try the latest version out](https://github.com/sschwartzman/newrelic-unix-plugin/blob/master/dist/newrelic_unix_plugin.tar.gz?raw=true) and let me know if that works for you.

**Comment by dmacisso** [comment]
Hi Seth.
I just installed plugin V3.5.1; but getting the same results.
https://rpm.newrelic.com/accounts/1231377/plugins/20410

**Comment by sschwartzman** [comment]
Can you put the output of "svmon -G -Ounit=KB -Otimestamp=on" in here or in a gist?

**Comment by sschwartzman** [comment]
I ran your script and figured out what you're doing. So here is my output when I run the svmon command:
               size       inuse        free         pin     virtual  available   mmode
memory        2.00G       1.97G       29.2M       1.04G       1.41G    504.11M     Ded
pg space    512.00M       7.61M

               work        pers        clnt       other
pin         955.48M          0K       7.09M     103.68M
in use        1.41G          0K     577.43M

So what you're saying is the "in use" under the "work" column actually refers to the memory in-use and the free memory is the total less that value. So I was using the "inuse" column of the first line, which reads 1.97gb in this case. I'm not an expert in AIX so can you explain to me the difference between these two figures?

**Comment by dmacisso** [comment]
Hi Seth, I don't consider myself to be an AIX export either. The formula that I use goes back a few years. I believe from a post on aix developers web site.  I do know the "client data"  includes the JFS2 file system cached data.  Since the OS grabs free memory to cache the file systems, I prefer to discount it when I calculate free memory.

**Comment by dmacisso** [comment]
The formula I used was based on the information in this post
http://www.aixhealthcheck.com/blog?id=255

**Comment by sschwartzman** [comment]
Reading that article and then looking back at the svmon output, I see the "virtual" and "available" columns in the first row, which look to be accurate. I will use those, as I'm not doing any math with the plugin (nor do I want to, as it creates room for error). Sound good?

**Comment by dmacisso** [comment]
Yes, Thank you..

**Comment by sschwartzman** [comment]
Ok, done! Can you try it out and let me know if it suits you?

**Comment by dmacisso** [comment]
Hi Seth
I installed V3.6, Unfortunately, I am not seeing any difference the memory stats.
https://rpm.newrelic.com/accounts/1231377/plugins/20410

https://rpm.newrelic.com/accounts/1231377/dashboard/13450008/page/4?tw%5Bend%5D=1472576131&tw%5Bstart%5D=1472574331

**Comment by sschwartzman** [comment]
Hmm, the metric names don't look right on your instance. I did up the version # to 3.6 and make a couple of tweaks after that. Can you try downloading the plugin again and trying it again? If it fails, please run the plugin in "debug", collect the logs and send them to me in a gist.

To run in debug, change `"log_level": "info"` to `"log_level": "debug"` in newrelic.json, and change `"debug": false` to `"debug": true` in plugin.json. Then, restart the agent. The output will all be written to newrelic_unix_plugin.log.

Sorry for the thrashing, hopefully we'll have this ironed out soon.

**Comment by dmacisso** [comment]
Got it!!
https://rpm.newrelic.com/accounts/1231377/plugins/20410
Thank you very much..

**Comment by sschwartzman** [comment]
Great! Thanks for persisting with me on this one.
