### ISSUE TITLE
How to add new commands?

### ISSUE THREAD

**Issue by zhil** [sschwartzman/newrelic-unix-plugin#28]
I am interested in adding new monitoring commands for ubuntu.
Something like

```
netstat -an|awk '/tcp/ {print $6}'|sort|uniq -c
```

it provide current connections status/count, like

```
758 TIME_WAIT
279 ESTABLISHED
30 SYN_SENT
3 LISTEN
1 FIN_WAIT2
```

It would be nice to collect that info and build graphs for it.
Is it possible with your plugin?

**Comment by sschwartzman** [comment]
You're welcome to branch the src to do that. You'd edit the "LinuxMetrics.java" file and create a new stanza matching the form of the other ones.
