### ISSUE TITLE
gsub/awk not working on Solaris 10 Sparc

### ISSUE THREAD

**Issue by OscarLopezEns** [sschwartzman/newrelic-unix-plugin#29]
Hi Seth,

pluginctl.sh is failing with the following error on a Solaris 10 Sparc server when trying to pull the java version:

```
awk: syntax error near line 1
awk: illegal statement near line 1
```

The specific Solaris version is:
_SunOS 5.10 Generic_150400-35 sun4v sparc sun4v_

Did some digging and apparently the "_gsub_" function used in "_awk_" in line 56 does not work well in Solaris 10: http://www.oaktable.net/content/solaris-awk-still-broken-after-all-these-years-0

I was able to workaround the issue by modifying line 56 to use "_**nawk**_" instead of "_awk_".

Letting you know so the same can be fixed on the script.

Thanks,
Oscar

**Comment by sschwartzman** [comment]
Thanks for bringing this to my attention, @OscarLopezEns . I fixed this by using an 'awk' command that does work on Solaris 10 - I tested it on my own Solaris 10 test bed. The latest version - which has lots of other tweaks - is posted. Give it a shot!

Thanks,
Seth

**Comment by OscarLopezEns** [comment]
Hi Seth!

Thanks for fixing! I have not had the opportunity to test it again on Solaris 10.
However I tested this today only this time it was a Solaris 8 / SunOs 5.8 machine.

Unfortunately, it failed (at least for Solaris 8):

> ./pluginctl.sh start
> Plugin location: /opt/newrelic/newrelic_unix_plugin
> awk: can't open /version/ {print $2}
> Java location: /usr/bin/java
> Java version:
> ./pluginctl.sh: test: argument expected

I fixed it using 'nawk' instead of using 'awk' on line 62:
`PLUGIN_JAVA_VERSION=`echo $PLUGIN_JAVA_VERSION_FULL | **n**awk -F '"' '/version/ {print $2}'``

Can you review this use case? I know Solaris 8 / SunOs 5.8 is way old but for some reason GE is still using it for some legacy systems it seems.

Thanks!!
Oscar

**Comment by sschwartzman** [comment]
I'd be willing to switch it to nawk if we can verify that it'll still work on Linux, AIX and OSX without anything special. I've never used nawk. Can you help me test it?

**Comment by sschwartzman** [comment]
The linux boxes I have don't have nawk installed, so I can't assume it's there. Same applies with OSX. So maybe I can do a check for if uname = solaris? Would that work for you?

**Comment by sschwartzman** [comment]
@OscarLopezEns I updated to run with 'nawk' if on Solaris... can you try it out?

https://raw.githubusercontent.com/sschwartzman/newrelic-unix-plugin/master/pluginctl.sh

**Comment by OscarLopezEns** [comment]
haha loved your comment "nawk for Solaris cuz Oscar said so ;)"

I don't have access to the Solaris 8 box anymore (actually I was guiding a sysadmin on the install), but will install the plugin on another Solaris box next week.
I did test it previously with 'nawk' though, and it worked.

It seems nawk is just a newer flavor of awk (there are others like gawk, for GNU distributions). So far on the 2 solaris plugin installs I've done (one 8 and another 10), nawk has worked on both cases.

I will do some research and check whether 'nawk' is available on any Solaris version.
Thanks a lot for your help Seth!! Keagan and our team appreciate it ;)

**Comment by sschwartzman** [comment]
Let's assume it's there then. This seems to work now. :)
