### ISSUE TITLE
Request size limit

### ISSUE THREAD

**Issue by OscarLopezEns** [sschwartzman/newrelic-unix-plugin#30]
Hey Seth,

Oscar bugging here again. SunOS 5.10 testing using latest plugin version. 

Just checking if you have you come across this error before?

> [2017-02-01 13:16:26,027] ERROR com.newrelic.metrics.publish.binding.Request - Failed server response: 413, {"error": "Request size is over 1 MiB limit"}

For some reason this SunOs 10 machine is going over the data limit when trying to send the data to NR.

Do you have any suggestion or have come across this issue before, for the plugin? Probably some commands unusually reporting a great amount of data for this machine in particular.

Thanks!
Oscar

**Comment by sschwartzman** [comment]
That's not something that's under my control really. What you could do is disable groups of metrics that you don't need or don't use much. Take a look in plugin.json to see the commands being run, and remove those you deem unnecessary. Note: Some aren't commands but are pointers to a command. Then take a look in SolarisMetrics.java to see what the actual command is, and what metrics are being collected.

You can also run the plugin in "debug" to see what all of the metrics are. To do that, set `"debug": true` in plugin.json, and `"log_level": "debug"` in newrelic.json. It will not send metrics, and instead write them to the log file.

**Comment by OscarLopezEns** [comment]
Thanks. This helps.
