### ISSUE TITLE
Don't use 'top' to determine linux memory usage

### ISSUE THREAD

**Issue by gmbenz** [sschwartzman/newrelic-unix-plugin#32]
Can't tell for sure how you're calculating it, but it sure seems like you're scraping the numbers out of top. Use 'free' instead.

Read this: http://www.linuxatemyram.com/

**Comment by sschwartzman** [comment]
You're welcome to contribute on this, the LinuxMetrics.java file is where I defined which commands are being scraped. I haven't had any other complaints about using top so I'm going to leave it as-is.
