### ISSUE TITLE
Unix plugin in AIX box is getting stopped automatically

### ISSUE THREAD

**Issue by HimanshuMaity** [sschwartzman/newrelic-unix-plugin#33]
Hi, I have applied Unix plugin for a AIX box using proper Newrelic license. It's giving proper result but after running some hours it's getting stopped. In the plugin log it did not show any error. I need your help to analyze the issue.

**Comment by HimanshuMaity** [comment]
Can anyone please help me on this?

**Comment by sschwartzman** [comment]
Do you still need help with this? I saw your other issue reqyest for APM help, now that you have the  plugin running.

**Comment by HimanshuMaity** [comment]
Thanks, I got my answer. APM setup is not possible for this plugin.
