### ISSUE TITLE
How to setup APM for AIX hosted application 

### ISSUE THREAD

**Issue by HimanshuMaity** [sschwartzman/newrelic-unix-plugin#34]
Hi,

I have setup Unix plugin from Chocolate factory(https://rpm.newrelic.com/accounts/1418048/plugins/directory/263) to get the server information. It is working fine and giving information properly. Now, I'm trying to setup APM for the application hosted on AIX box. But, still not able to do that.

Can anyone please help me on this?

Thanks in advance.

**Comment by sschwartzman** [comment]
Hi Himanshu,

The Unix plugin has nothing to do with your APM deployment, so you'll need to reach out to New Relic support for help with that. Sorry.

Thanks,
Seth
