### ISSUE TITLE
Disk

### ISSUE THREAD

**Issue by JerseyT** [sschwartzman/newrelic-unix-plugin#35]
Is there way to exclude CD from monitoring? It showing up as fullest disk at 100%. Please advise. 

Overall, its a great pluggin.

Thank you

**Comment by sschwartzman** [comment]
Yes, it can be done. Which OS, so I can check what the "exclude" parameter is for df?

**Comment by sschwartzman** [comment]
I updated it for linux to exclude "iso9660", "cdfs" and "hsfs" - try out the latest version and let me know if it works for you.

**Comment by JerseyT** [comment]
This for redhat linux. Thank you.

**Comment by sschwartzman** [comment]
I added the code to do the exclusion for linux in the latest version. It excludes CDFS, ISO9660 and HSFS file systems. Can you try it out and let me know if it works?

**Comment by JerseyT** [comment]
Where can I get that latest update? Website to download still states that updated 1/24.

**Comment by sschwartzman** [comment]
You can always get the latest here: https://github.com/sschwartzman/newrelic-unix-plugin/blob/master/dist/newrelic_unix_plugin.tar.gz?raw=true

**Comment by hubdotcom** [comment]
Also please disable monitoring of Devfs - shows as 100% full on OSX

**Comment by hubdotcom** [comment]
Both running macOS Sierra
![screenshot 2017-05-30 15 05 17](https://cloud.githubusercontent.com/assets/5274747/26587140/68d36d98-4549-11e7-8d22-e4319158af8e.png)

![screenshot 2017-05-30 15 05 49](https://cloud.githubusercontent.com/assets/5274747/26587163/7baaf9cc-4549-11e7-9867-e3095f8270c6.png)

**Comment by sschwartzman** [comment]
Please try the new plugin (which reports to NR Insights) and report any issues there: https://github.com/newrelic-experts/unix-infra-monitor
