### ISSUE TITLE
Data not reporting to New Relic from Solaris OS server 

### ISSUE THREAD

**Issue by MounikaPearl** [sschwartzman/newrelic-unix-plugin#37]
Installed the New Relic Solaris plug in on the server but the data is not reporting, when installed the latest plugin again , still the data is not reporting and also gave the proper proxy and port, license key, java path, plug in path. The server reports data for sometime after installing the plug in and again it stops reporting data.
Can someone suggest on this?

**Comment by sschwartzman** [comment]
Please try the new plugin (which reports to NR Insights) and report any issues there: https://github.com/newrelic-experts/unix-infra-monitor
