### ISSUE TITLE
Process Instance Count metric generating false alerts

### ISSUE THREAD

**Issue by MHAbbas** [sschwartzman/newrelic-unix-plugin#38]
Hi,

We are monitoring processes through UNIX Plugin:
We are defining metric manually in the condition:
Component/Processes/java/Instance Count[processes] < 6 units for at least 10 minutes
But is not working as expected and generating quite many false alerts.

Regards,
Abbas

**Comment by sschwartzman** [comment]
Can you provide a link to the account and alert in question?

**Comment by sschwartzman** [comment]
Please try the new plugin (which reports to NR Insights) and report any issues there: https://github.com/newrelic-experts/unix-infra-monitor
