### ISSUE TITLE
Error: Could not find or load main class com.chocolatefactory.newrelic.plugins.unix.Main

### ISSUE THREAD

**Issue by mderubertis** [sschwartzman/newrelic-unix-plugin#4]
In plugin.log. Any suggestions?

**Comment by sschwartzman** [comment]
Can you post a ZIP of the agent, including log files?

**Comment by nytsua** [comment]
I'm seeing this same issue with the latest version that I downloaded from New Relic Plugin Central: https://rpm.newrelic.com/accounts/874863/plugins/directory/263 . 

When I downloaded a version from the url in the readme that one works: https://github.com/sschwartzman/newrelic-unix-plugin/blob/master/dist/newrelic_unix_plugin.tar.gz?raw=true . 

After setting up the one from the link in the readme it is working, however it's telling me a new version is available which is identical to the one in the New Relic Plugin Central.

I don't have a log file anymore but it was just one line (the description of this bug):
Error: Could not find or load main class com.chocolatefactory.newrelic.plugins.unix.Main

**Comment by nytsua** [comment]
Sorry, I don't think this is an issue, at least for me. I downloaded the full master zip from github and tried to use that. I missed the dist folder which contains the tar.gz that is meant to be installed.

**Comment by sschwartzman** [comment]
I've updated the download link to point to the correct archive file. @mderubertis can you try to download and re-test?

**Comment by mderubertis** [comment]
Thanks it works now! Sorry I did not answer earlier. Never received a notification from GitHub about your reply.
