### ISSUE TITLE
Change Server Label Name in New Relic Portal

### ISSUE THREAD

**Issue by theCodeMachine** [sschwartzman/newrelic-unix-plugin#45]
Hi Seth,

We would like to change the Server Name label(Instead of Host name) reported in New Relic dashboard. So just wanted to check if there is a way to change the Server Name Label through plugin configuration? If not can you please consider this as a feature request and add a way to change the server name.

Thanks.

**Comment by sschwartzman** [comment]
It's in there: https://github.com/sschwartzman/newrelic-unix-plugin#optional-configurations-for-pluginjson

**Comment by theCodeMachine** [comment]
Thanks :)
