### ISSUE TITLE
Post to insights

### ISSUE THREAD

**Issue by JesusGroba** [sschwartzman/newrelic-unix-plugin#47]
Hi, I'm trying to use this plugin to post the metrics to insights, I can't find where it do the post to New Relic so I can add the lines push the metrics to insights.

Could you help me pls?

**Comment by sschwartzman** [comment]
This plugin is not written to send metrics to Insights. It would need to be rewritten to make REST calls to the Insights API.

**Comment by sschwartzman** [comment]
Update: I've been working on a new version of the plugin, which does report to Insights. I will update you on when it becomes available.
