### ISSUE TITLE
NR Solaris Plugin Question

### ISSUE THREAD

**Issue by MichaelRSmith-JH** [sschwartzman/newrelic-unix-plugin#50]
Hello -we are wondering if the graphs showing resource utilization and load averages captured by NR plugin reflects the activity on the Local Zone or is that a reflection of activity on the Global Zone server that is HOSTING the Local zone?

**Comment by sschwartzman** [comment]
Here are the commands I'm running at command-line to get that data. I don't know if they're return local or global zone, but you can use the man page, running at command-line, and the almighty Google to figure that out:

For Solaris 10:
`prstat -c 1 2` for Load Average
`iostat -c 1 2` for CPU utilization
`kstat -p unix::system_pages` for Memory and Page utilization

For Solaris 10:
`top -b` for Load Average, CPU and Memory utilization
`kstat -p unix::system_pages` for (more) Memory and Page utilization

**Comment by MichaelRSmith-JH** [comment]
Hello – Thanks for the information!!
