### ISSUE TITLE
Centos 7.4 doesn't record Memory stats

### ISSUE THREAD

**Issue by itek09** [sschwartzman/newrelic-unix-plugin#52]
Hello,

first of all, thank you for this plugin.

I'm using the plugin on several servers (all Linux) and I'm experimenting an issue related to memory stats collection.

On Debian's like Server, the stats are collected correctly, but on CentOs Servers the plugin cannot collect any memory related data.

Checking your code, the plugin is collecting the data from "top -b -n1" command. If we put this command in terminal, we can see the next differences:

DEBIAN OUTPUT:
top - 12:50:34 up 157 days,  2:04,  1 user,  load average: 0.41, 1.14, 2.86
Tasks: 140 total,   1 running, 138 sleeping,   0 stopped,   1 zombie
%Cpu(s):  6.7 us,  2.0 sy,  0.0 ni, 90.9 id,  0.1 wa,  0.0 hi,  0.4 si,  0.0 st
**KiB Mem:  16460676 total,  5494348 used, 10966328 free,   222532 buffers
KiB Swap:  4284412 total,    26476 used,  4257936 free,  3980280 cached**

CENTOS OUTPUT:
top - 12:50:22 up 10 days,  8:44,  2 users,  load average: 0.06, 0.19, 0.29
Tasks: 1045 total,   1 running, 1044 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.1 us,  0.8 sy,  0.0 ni, 93.4 id,  0.6 wa,  0.0 hi,  0.1 si,  0.0 st
**KiB Mem : 10564166+total, 26602835+free, 45327065+used, 33711763+buff/cache
KiB Swap: 33554428 total, 33554428 free,        0 used. 59909139+avail Mem**

I think the parser is going wrong with the "+" character and the data fails to be collected.

Can you check the issue?

Really thanks

**Comment by Reiner030** [comment]
When I was setup this plugin to replace in May deactivated Servers part of NR it was working very well with Debian Jessie/8.
When now upgrading our instances to Debian Stretch/9 I run also in an equal problem.
It seems that the top header output was modified - I see there a space for ````Mem :````
and at end of same line a mixed buff/cache instead separated values and swapped used/free values also:

* Debian Jessie:
````
# top -b -n1 | head
top - 20:17:12 up 85 days,  2:51,  1 user,  load average: 0.15, 0.36, 0.47
Tasks: 138 total,   1 running, 137 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,  0.3 id,  0.0 wa,  0.0 hi,  0.0 si, 99.6 st
KiB Mem:   4049024 total,  3553216 used,   495808 free,   195172 buffers
KiB Swap:  1048572 total,    27632 used,  1020940 free.  1329460 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0  200424   4952   3608 S   0.0  0.1  47:10.78 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.02 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   2:00.96 ksoftirqd/0
...
````

* Debian Stretch:
````
# top -b -n1 | head
top - 20:17:32 up  1:10,  2 users,  load average: 0.02, 0.19, 0.26
Tasks: 163 total,   1 running, 162 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.7 us,  2.9 sy,  0.0 ni, 88.4 id,  0.2 wa,  0.0 hi,  0.4 si,  0.4 st
KiB Mem :  8177876 total,  4256748 free,  1173368 used,  2747760 buff/cache
KiB Swap:  8388604 total,  8388604 free,        0 used.  6628676 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0  139632   7368   5216 S   0.0  0.1   0:01.22 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:01.94 ksoftirqd/0
...
````

**Comment by VithalKumar** [comment]
Having similar problem on Red Hat Enterprise Linux Server release 7.4 (Maipo)

top - 12:28:34 up 30 days, 13:38,  1 user,  load average: 0.15, 0.28, 0.28
Tasks: 208 total,   1 running, 198 sleeping,   0 stopped,   9 zombie
%Cpu(s):  1.6 us,  3.1 sy,  0.0 ni, 95.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 15677344 total,   249996 free, 11554668 used,  3872680 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2742944 avail Mem
....

**Comment by sschwartzman** [comment]
Please try the new plugin (which reports to NR Insights) and report any issues there: https://github.com/newrelic-experts/unix-infra-monitor

**Comment by Reiner030** [comment]
Sadly the "great new infrastructure monitoring" is not included in APM monitoring as a basic variant and extra costs for normally inclusive services makes no sense - especially because the "great new infrastructure monitoring" couldn't even handle things that the "good old Nagios / Icinga" could do easily.
(If it wouldn't the case you haven't migrated this module to new system :smile: ...)

Because there is no compilation part in the readme:
Do you have some tips / is there something special to check to compile this module?
Thanks.

**Comment by wuservices** [comment]
@Reiner030 I believe the new plugin reports to Insights, not Infrastructure, so you don't necessarily have to pay more...

@sschwartzman However, you don't quite get the same retention as the plugin did. At least for me, I get 8 days of retention for the plugin, but only 24 hours of retention for custom events in Insights. I'm assuming the new plugin would log custom events and in this case, less retention would certainly be a downside even though I love the customizability of Insights.
