### ISSUE TITLE
Data Not Showing for machine running SunOS

### ISSUE THREAD

**Issue by shabzshkh** [sschwartzman/newrelic-unix-plugin#53]
Hi Team,

None of the stats are showing up when we installed new relic plugin on SunOS. We are getting the below error:

./pluginctl.sh start

Plugin location: /opt/unix-infra-monitor

Java location: /usr/bin/java

Java version: 1.6.0_21

grep: illegal option -- q

Usage: grep -hblcnsviw pattern file . . .

Running as plugin that posts directly to Insights.

./pluginctl.sh: syntax error at line 236: `admin_api_key=$' unexpected

Can someone please advise.

Regards,
Shahbaz

**Comment by sschwartzman** [comment]
In the script, change the 1st line to #!/bin/ksh or #!/bin/bash and re-run.

Note: This is deprecated, please try the newer version, which is actively maintained: https://github.com/newrelic/newrelic-unix-monitor
