### ISSUE TITLE
Entity not visible in Plugin while creating Alert in Newrelic

### ISSUE THREAD

**Issue by Aishwaryah89** [sschwartzman/newrelic-unix-plugin#54]
I was setting alert for a particular server and in the condition i am not able to view the entity. From the server side i checked and confirmed that the entity is up and running.
In the below link 
https://alerts.newrelic.com/accounts/1306259/policies/317109/conditions/9007419/edit
prd1live-ess2.prd.arcadiagroup.ltd.uk and prd1live-ihs4.prd.arcadiagroup.ltd.uk are not visible
[Alert issue.docx](https://github.com/sschwartzman/newrelic-unix-plugin/files/3013084/Alert.issue.docx)

**Comment by sschwartzman** [comment]
This plugin is deprecated, please use New Relic Unix Monitor: https://github.com/newrelic/newrelic-unix-monitor
