### ISSUE TITLE
just added the latest version to our AIX server, cant see cpu stats

### ISSUE THREAD

**Issue by potgieterdl** [sschwartzman/newrelic-unix-plugin#6]
Hey,

I havent used the plugin before but we got it installed and pushing through to new relic. Awesome work with this, exactly what we needed.

I`m having a issue seeing cpu and memory coming through. As there a certain command that i need to have access to for those two?

**Comment by sschwartzman** [comment]
Hi Derick,

I'm glad to hear it's useful! Do you remember working with me back in 2013 and we discussed AIX monitoring? Well, I got tired of being asked for it so often and wrote this plugin. :)

The commands I'm using on AIX for CPU and Memory are lparstat (for CPU) and svmon (for memory). Does your user have access to both?

If you do have access to them, can you do the following:
1. Run the agent for a minute in debug mode. To do that, use the "plugin.json.aix-debug" file as your plugin.json file, and change logging to "debug" in newrelic.json. Then restart the agent and run it for a couple minutes.
2. Run these two commands at command-line as the user running your agent:
lparstat 1 1
svmon -G -Ounit=KB
3. Take the log/output from steps 1 & 2 and post them to github as a gist: https://gist.github.com/

Thanks!
--Seth

**Comment by millermars** [comment]
Hi -  I am having the same issue with my AIX  server.  I followed the steps above for the requested information.  The gist is:  millermars/newrelic_aix_cpu_issue

**Comment by sschwartzman** [comment]
Thanks for that! I found the issue - basically the server where I was testing AIX was reporting slightly differently from both of yours. I added a trailing wildcard on the regex for lparstat and vmstat to account for that.

Please download the latest version (you can just replace bin/newrelic_unix_plugin.jar from the new package), restart the plugin and then let me know how it looks after a couple of minutes.

--Seth

**Comment by millermars** [comment]
Seth - 

Thanks for the quick turn-around.  That seems to have done the trick.  I am receiving data now.

-m

**Comment by sschwartzman** [comment]
Great!! Glad it was a simple enough fix.
