### ISSUE TITLE
sparc host not reporting CPU/load info

### ISSUE THREAD

**Issue by CAguayo** [sschwartzman/newrelic-unix-plugin#7]
Hi there,

I installed this plugin on a Sparc/Solaris host, uname says,

  SunOS camsvnp1 5.10 Generic_147440-23 sun4v sparc SUNW,T5240 Solaris

and I get all the data promised *except* the CPU and Load Average data.

Symptom is a blank chart for both, the threads, memory, disk, and network charts look fine.

Is this something I could fix, or anything I could send along to help diagnose the underlying issue?

Many thanks!

Carlos
carlos.aguayo@nike.com

**Comment by sschwartzman** [comment]
Have you upgraded to the latest version and followed the directions for Solaris 10? I updated it to handle the fact that Solaris 10 lacks "top".

Please let me know if you have tried it or can try it.

Thanks,
Seth

**Comment by sschwartzman** [comment]
By the way, the difference in the steps to follow is to copy /config/plugin.json.solaris_10 to /config/plugin.json. Otherwise the install & config is the same as before.

**Comment by CAguayo** [comment]
Thank you, I'll have to try this when I get back, away for a couple of weeks!

I *really* appreciate your sharing this code, gets me out of a bind.

Cheers,

Carlos

**Comment by CAguayo** [comment]
So it looks to me like we do have top, but it's installed at /usr/local/bin/top, and I'm guessing that the agent is not finding it.  Is there a config way to fully qualify the path?

**Comment by CAguayo** [comment]
On the other hand, once I followed this suggestion, I started getting all the charts, not sure if top does the same job more efficiently, but it may as well be a "case closed."  Thanks again for your help!
