### ISSUE TITLE
v3.4 - OS X 10.6.8 Server - Disk Size Not Reporting Properly

### ISSUE THREAD

**Issue by seth-reeser** [sschwartzman/newrelic-unix-plugin#9]
Disks reporting in the Plugins UI dashboard:

![screen shot 2016-01-15 at 10 43 54 am](https://cloud.githubusercontent.com/assets/6510351/12357262/e59f3178-bb74-11e5-8a72-daf6c77b805a.png)

Actual df:
<img width="456" alt="screen shot 2016-01-15 at 10 46 27 am" src="https://cloud.githubusercontent.com/assets/6510351/12357332/405a10e2-bb75-11e5-90c0-01eb37dd622d.png">

**Comment by sschwartzman** [comment]
Can you run "df -k" on your server instead of just "df", and compare that to the plugin #s? By just running "df", you're looking at the block counts not kilobytes.
